# Generated by Django 4.0.5 on 2022-07-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='static/images')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('status', models.BooleanField(default=False, help_text='0=default, 1=Trending')),
            ],
        ),
    ]
