# Generated by Django 4.0.5 on 2022-07-25 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_item_brand_item_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
